### ISSUE TITLE
Don't use named params for IERC20.approve (or use more recent OZ release)

### ISSUE THREAD

**Issue by ccashwell** [0xSplits/splits-contracts-monorepo#27]
## Problem (nit)

It's unnecessarily challenging to meaningfully test integration with Splits V2 within any project context which uses the latest release of OpenZeppelin contracts. While it is fine to expect folks to mock out the implementation in tests, you don't provide interfaces or mocks to facilitate that process, and attempting to use the package off-the-shelf in an existing Foundry project which uses the latest major release leads to compilation errors.

<img width="791" alt="image" src="https://github.com/0xSplits/splits-contracts-monorepo/assets/184242/5e00c945-8d67-4474-9277-e9ab3373da85">

## Cause

[packages/splits-v2/package.json](https://github.com/0xSplits/splits-contracts-monorepo/blob/main/packages/splits-v2/package.json) specifies an older release of `@openzeppelin/contracts` (^4.9.3 from July 2023) that contains their "old" IERC20 interface, and [you're using named args to `IERC20.approve`](https://github.com/0xSplits/splits-contracts-monorepo/blob/main/packages/splits-v2/src/splitters/pull/PullSplit.sol#L113) with the old `amount` param (renamed to `value` in ^v5.0.0)

## Solution

Without changing dependencies at all, this is resolved simply by not using named args to `IERC20.approve`

**Comment by r0ohafza** [comment]
Hey @ccashwell, thanks for opening an issue and highlighting this pain point. Can you share some context with your dev setup? What I am trying to understand is if we can have two oz versions installed, you could use remappings to resolve this issue, believe this would only be possible if you were doing it in a npm repo. I understand this is not ideal, exploring other options as well in the mean time.

**Comment by ccashwell** [comment]
I'm using a pure Foundry setup, not an npm project with remappings from `node_modules`, so there's no easy way to install multiple versions of the same dependency.

**Comment by wminshew** [comment]
@ccashwell want to make sure this isn't blocking you atm -- I believe you can just go make the change directly yourself in the imported `lib/splits-contracts-monorepo/` folder and it should all just work (minus the reproducibility). We'll come up with a longer term solution shortly--sorry for the hassle

**Comment by ccashwell** [comment]
Not a blocker at all, just a nit. I directly changed the dependency locally which is enough to keep me going for now.

**Comment by wminshew** [comment]
current thinking here is we'll 1/ add a note to the readme about integrating w/ npm vs git submodules and 2/ add a separate branch w/o named args for people using the latter

**Comment by wminshew** [comment]
until foundry adds proper support for package management, we prefer this (having launched several projects solely with foundry, the package management almost always becomes an issue and node provides an easy fix). We're comfortable being opinionated about what we think is best practice, even if it isn't common today

keeping the main branch inline with what's deployed and verified onchain is valuable and worth the add'l overhead of the branch we think atm, although I could see this changing in the future (technically the compiled bytecode should still be the same, minus the appended ipfs hash)

out of curiosity, why not use fork testing?
